version: '3'
services:
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx-server/logs:/var/log/nginx
      - ./nginx-server/default.conf:/etc/nginx/conf.d/default.conf
      - ./:/srv/www
    depends_on:
      - phpfpm

  phpfpm:
    build:
      context: .
      dockerfile: docker/phpfpm/Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/srv/www
      - ./docker/phpfpm/default.conf:/usr/local/etc/php-fpm.d/default.conf