index:
    path: /
    controller: App\Controller\PaymentController::index

shop:
    path: /shop
    controller: App\Controller\PaymentController::shop

authorize:
    path: /load/{paymentType}
    controller: App\Controller\PaymentController::load