index:
    path: /
    controller: App\Controller\PaymentController::index

shop:
    path: /shop
    controller: App\Controller\PaymentController::shop

authorize:
    path: /load/{paymentType}/{sourceId}
    controller: App\Controller\LoadController::load

charge:
    path: /charge/{sourceId}
    controller: App\Controller\LoadController::charge